(function(){
const ACC='wts_member_accounts_v1', FAN='wts_fan_accounts_v1';
const $=s=>document.querySelector(s);
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function member(){const u=localStorage.getItem('wts_member_session'); if(!u)return null; return get(ACC,[]).find(a=>a.username===u)||null}
function fan(){const u=localStorage.getItem('wts_fan_session'); if(!u)return null; return get(FAN,[]).find(a=>a.username===u)||null}
function me(){return member()||fan()}
function profileData(){const x=me(); if(!x)return null; if(x.type==='member'||x.group){return {type:'member',data:x,photo:x.photo||'',cover:x.cover||'',name:x.name||'NAME',group:x.group||'WAY TO SHINE',oshi:x.oshi||0,kami:x.kamiCount||0,star:x.star||0,like:x.likes||0,badge:'+ MEMBER',sub:(x.group||'')+' • MEMBER'}} const prof=get('wts_fan_profile_v1',{})[x.username]||{}; return {type:'fan',data:x,photo:prof.photo||'',cover:prof.cover||'',name:prof.name||x.name||'NAME',group:'WAY TO SHINE FAN',oshi:prof.oshi||0,kami:prof.kamiCount||0,star:Number(x.star||100),like:prof.likes||0,badge:'+ Kami-Oshi',sub:'FAN ACCOUNT'}}
function apply(){const p=profileData(); if(!p){location.href='login.html?return=account.html';return} $('#profileName').textContent=p.name;$('#profileSub').textContent=p.sub;$('#profileBadge').textContent=p.badge;$('#statOshi').textContent=Number(p.oshi).toLocaleString();$('#statKami').textContent=Number(p.kami).toLocaleString();$('#statStar').textContent=Number(p.star).toLocaleString();$('#statLike').textContent=Number(p.like).toLocaleString();
const av=$('#profileAvatar'); av.textContent=p.photo?'':String(p.name).trim().slice(0,1).toUpperCase(); av.style.backgroundImage=p.photo?`url("${p.photo.replace(/"/g,'')}" )`:''; $('#profileCover').style.backgroundImage=p.cover?`linear-gradient(180deg,rgba(0,0,0,.08),rgba(0,0,0,.18)),url("${p.cover.replace(/"/g,'')}")`:''; $('#accountTitle').textContent=p.type==='member'?'MEMBER ACCOUNT':'MY ACCOUNT';
$('#starAction').onclick=()=>location.href='spark.html'; $('#editProfileBtn').onclick=()=>openModal(p); $('#editAvatarBtn').onclick=()=>openModal(p); $('#editCoverBtn').onclick=()=>openModal(p); $('#logoutBtn').onclick=()=>{localStorage.removeItem('wts_member_session');localStorage.removeItem('wts_fan_session');localStorage.removeItem('wts_logged');location.href='index.html'};
const tl=$('#accountTimeline'); if(p.type==='member') tl.dataset.author=p.data.username; if(window.WTSTimeline)WTSTimeline.render(tl, 'ALL');}
function openModal(p){$('#editName').value=p.name;$('#editPhoto').value=p.photo.startsWith('data:')?'':p.photo;$('#editCover').value=p.cover.startsWith('data:')?'':p.cover;$('#profileModal').setAttribute('aria-hidden','false')}
function close(){ $('#profileModal').setAttribute('aria-hidden','true'); $('#saveMsg').textContent=''}
$('#modalClose').onclick=close; $('#profileModal').onclick=e=>{if(e.target.id==='profileModal')close()};
async function fileData(file){if(!file)return '';return await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
$('#saveProfile').onclick=async()=>{const p=profileData();if(!p)return;let photo=$('#editPhoto').value.trim(),cover=$('#editCover').value.trim();const pf=$('#photoFile').files[0],cf=$('#coverFile').files[0];if(pf)photo=await fileData(pf);if(cf)cover=await fileData(cf);const name=$('#editName').value.trim()||'NAME';if(p.type==='member'){const arr=get(ACC,[]),i=arr.findIndex(a=>a.username===p.data.username);if(i>=0){arr[i]={...arr[i],name,photo,cover};set(ACC,arr);localStorage.setItem('wts_username',name)}}else{const prof=get('wts_fan_profile_v1',{});prof[p.data.username]={...(prof[p.data.username]||{}),name,photo,cover};set('wts_fan_profile_v1',prof);const arr=get(FAN,[]),i=arr.findIndex(a=>a.username===p.data.username);if(i>=0){arr[i].name=name;set(FAN,arr)}localStorage.setItem('wts_username',name)}close();apply()};
apply();
})();