(()=>{
const K={settings:'wts_settings_v2',members:'wts_members_v2',accounts:'wts_accounts_v2',fan:'wts_fans_v2',session:'wts_session_v2',songs:'wts_songs_v2',schedule:'wts_schedule_v2',banners:'wts_banners_v2',works:'wts_works_v2',events:'wts_major_events_v2',merch:'wts_merch_v2',inventory:'wts_inventory_v2',redeem:'wts_redeem_v2',spark:'wts_spark_v2',timeline:'wts_timeline_v2'};
const defaults={settings:{appName:'WAY TO SHINE',logo:'✦',tokenName:'TOKEN',tokenIcon:'🪙',starName:'STAR',starIcon:'⭐',background:'linear-gradient(180deg,#fff 0%,#fbf9ff 100%)',currencies:[]},members:{TLP48:[],EDN48:[]},accounts:[],fan:[],songs:{TLP48:[],EDN48:[]},schedule:{TLP48:[],EDN48:[]},banners:{TLP48:[],EDN48:[]},works:{TLP48:[],EDN48:[]},events:[],merch:[],inventory:[],redeem:[],spark:{votes:{},members:[]},timeline:[]};
function read(k,d){try{return JSON.parse(localStorage.getItem(k)??JSON.stringify(d))}catch{return d}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v));return v}
function settings(){return {...defaults.settings,...read(K.settings,defaults.settings)}}
function seed(){if(!localStorage.getItem(K.settings))write(K.settings,defaults.settings);if(!localStorage.getItem(K.members))write(K.members,defaults.members);if(!localStorage.getItem(K.accounts))write(K.accounts,defaults.accounts);if(!localStorage.getItem(K.fan))write(K.fan,defaults.fan);if(!localStorage.getItem(K.songs))write(K.songs,defaults.songs);if(!localStorage.getItem(K.schedule))write(K.schedule,defaults.schedule);if(!localStorage.getItem(K.banners))write(K.banners,defaults.banners);if(!localStorage.getItem(K.works))write(K.works,defaults.works);if(!localStorage.getItem(K.events))write(K.events,defaults.events);if(!localStorage.getItem(K.merch))write(K.merch,defaults.merch);if(!localStorage.getItem(K.inventory))write(K.inventory,defaults.inventory);if(!localStorage.getItem(K.redeem))write(K.redeem,defaults.redeem);if(!localStorage.getItem(K.spark))write(K.spark,defaults.spark);if(!localStorage.getItem(K.timeline))write(K.timeline,defaults.timeline)}
function session(){const s=read(K.session,null);if(!s)return null;let arr=s.type==='member'?read(K.accounts,[]):read(K.fan,[]);return arr.find(x=>x.username===s.username)||null}
function login(account){write(K.session,{type:account.type||'fan',username:account.username});if(account.type==='fan'&&!Number.isFinite(Number(account.star)))account.star=0;return account}
function logout(){localStorage.removeItem(K.session);location.href='index.html'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(v){return Number(v||0).toLocaleString('en-US')}
function fileData(file){return new Promise((res,rej)=>{if(!file)return res('');const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
function groupTheme(g){return g==='TLP48'?'tlp':'edn'}
function getBalance(type='token'){const s=session();if(!s)return 0;if(s.type==='member')return Number(s.token||0);return Number(s[type]||0)}
function changeBalance(type,delta){const s=session();if(!s)return false;const key=type==='star'?'star':type;let arr=s.type==='member'?read(K.accounts,[]):read(K.fan,[]);const i=arr.findIndex(x=>x.username===s.username);if(i<0)return false;arr[i][key]=Math.max(0,Number(arr[i][key]||0)+Number(delta));write(s.type==='member'?K.accounts:K.fan,arr);return true}
function ensureDemo(){seed();}
function applyTheme(root=document.body){const s=settings();document.documentElement.style.setProperty('--app-bg',s.background||defaults.settings.background);document.documentElement.style.setProperty('--app-name',JSON.stringify(s.appName));document.querySelectorAll('[data-app-logo]').forEach(x=>x.textContent=s.logo||'✦');document.querySelectorAll('[data-app-name]').forEach(x=>x.textContent=s.appName||'WAY TO SHINE')}
window.WTS={K,defaults,read,write,settings,seed,session,login,logout,esc,fmt,fileData,groupTheme,getBalance,changeBalance,applyTheme};ensureDemo();document.addEventListener('DOMContentLoaded',()=>applyTheme());
})();