(function(){
const ACC='wts_member_accounts_v1', POSTS='wts_timeline_v1'; const root=document.getElementById('profileRoot');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function get(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}
function initials(n){return String(n||'M').trim().slice(0,1).toUpperCase()}
function fmt(d){return new Intl.DateTimeFormat('th-TH',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(d))}
const u=new URLSearchParams(location.search).get('username'); const me=get(ACC,[]).find(x=>x.username===u);
if(!me){root.innerHTML='<section class="member-not-found"><div>✦</div><h1>MEMBER NOT FOUND</h1><p>ยังไม่มี Member Account นี้</p></section>';return}
document.title=me.name+' • '+me.group;document.getElementById('topName').textContent=me.name;
const ps=get(POSTS,[]).filter(p=>p.username===me.username).sort((a,b)=>b.createdAt-a.createdAt); const stars=Number(me.stars||0), likes=Number(me.likes||0), oshi=Number(me.oshi||0);
function card(p){return `<article class="timeline-post"><div class="timeline-post-head"><div class="timeline-avatar" style="${p.photo?'background-image:url('+encodeURI(p.photo)+')':''}">${p.photo?'':esc(initials(p.name))}</div><div class="timeline-author"><b>${esc(p.name)}</b><small>${esc(p.group)} · ${fmt(p.createdAt)}</small></div><button class="timeline-more">•••</button></div>${p.text?`<div class="timeline-text">${esc(p.text).replace(/\n/g,'<br>')}</div>`:''}${p.media?`<img class="timeline-media" src="${esc(p.media)}" alt="Post media" loading="lazy" onerror="this.style.display='none'">`:''}<div class="timeline-actions"><span>⭐ <b>${Number(p.stars||0).toLocaleString()}</b> STAR</span><span>♡ <b>${Number(p.comments||0)}</b> Comments</span></div><div class="timeline-buttons"><button class="timeline-action send-profile-star" data-id="${esc(p.id)}">⭐ Send Star</button><button class="timeline-action" onclick="alert('ระบบ Comment พร้อมเชื่อมต่อฐานข้อมูลได้')">💬 Comment</button></div></article>`}
root.innerHTML=`<section class="public-member-profile ${me.group==='TLP48'?'tlp-profile':'edn-profile'}"><div class="member-cover" style="${me.cover?'background-image:url('+encodeURI(me.cover)+')':''}"><div class="cover-shine"></div></div><div class="member-profile-main"><div class="member-profile-avatar" style="${me.photo?'background-image:url('+encodeURI(me.photo)+')':''}">${me.photo?'':esc(initials(me.name))}</div><div class="kami-pill">+ Kami-Oshi</div><h1>${esc(me.name)}</h1><p class="member-symbol">${esc(me.symbol||'✦')}</p></div><div class="member-stats"><div><b>${oshi.toLocaleString()}</b><span>Oshi</span></div><div><b>${stars.toLocaleString()}</b><span>STAR</span></div><div><b>${likes.toLocaleString()}</b><span>Like</span></div><div><b>${ps.length}</b><span>Posts</span></div></div><div class="member-actions"><button class="member-star-btn" id="sendStar">⭐ STAR</button></div></section><section class="member-catchup-title"><span>✦</span><b>Timeline</b><small>${esc(me.group)} • ${esc(me.name)}</small></section><section class="section profile-posts"><div class="timeline-list">${ps.length?ps.map(card).join(''):`<div class="timeline-empty"><div>✦</div><b>ยังไม่มีโพสต์</b><span>สมาชิกยังไม่ได้โพสต์ใน Timeline</span></div>`}</div></section>`;
function sendStar(){const amount=prompt('จำนวน STAR ที่ต้องการส่ง', '1');const n=Number(amount);if(!Number.isFinite(n)||n<=0)return;const fan=Number(localStorage.getItem('wts_star')||0);if(fan<n)return alert('STAR ของคุณไม่เพียงพอ');localStorage.setItem('wts_star',String(fan-n));const a=get(ACC,[]),x=a.find(z=>z.username===me.username);if(x){x.stars=Number(x.stars||0)+n;localStorage.setItem(ACC,JSON.stringify(a));}location.reload()}
document.getElementById('sendStar').onclick=sendStar;document.querySelectorAll('.send-profile-star').forEach(b=>b.onclick=sendStar);
})();