(function(){
const KEY='wts_timeline_v1',ACC='wts_member_accounts_v1';const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));const fmtDate=d=>new Intl.DateTimeFormat('th-TH',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(d));const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};const posts=()=>get(KEY,[]);const members=()=>get(ACC,[]);const current=()=>{const u=localStorage.getItem('wts_member_session');return u?members().find(a=>a.username===u)||null:null};const initials=n=>String(n||'M').trim().slice(0,1).toUpperCase();
function media(p){if(!p.media)return '';const url=esc(p.media);if(/\.(mp4|webm|ogg)(\?|#|$)/i.test(p.media))return `<video class="timeline-media" controls playsinline src="${url}"></video>`;return `<img class="timeline-media" src="${url}" alt="Post media" loading="lazy" onerror="this.style.display='none'">`}
function card(p){return `<article class="timeline-post" data-id="${esc(p.id)}"><div class="timeline-post-head"><div class="timeline-avatar" style="${p.photo?'background-image:url('+encodeURI(p.photo)+')':''}">${p.photo?'':esc(initials(p.name))}</div><div class="timeline-author"><b>${esc(p.name)}</b><small>${esc(p.group)} · ${fmtDate(p.createdAt)}</small></div><button class="timeline-more" aria-label="More">•••</button></div>${p.text?`<div class="timeline-text">${esc(p.text).replace(/\n/g,'<br>')}</div>`:''}${media(p)}<div class="timeline-actions"><span>⭐ <b>${Number(p.stars||0).toLocaleString()}</b> STAR</span><span>♡ <b>${Number(p.comments||0)}</b> Comments</span></div><div class="timeline-buttons"><button class="timeline-action" data-star="${esc(p.id)}">⭐ Send Star</button><button class="timeline-action" data-comment="${esc(p.id)}">💬 Comment</button></div></article>`}
function render(root,forcedGroup){const group=forcedGroup||root.dataset.group||'ALL';const author=root.dataset.author||'';let list=posts().filter(p=>(group==='ALL'||p.group===group)&&(!author||p.username===author)).sort((a,b)=>b.createdAt-a.createdAt);const me=current();root.innerHTML=`<div class="timeline-head"><div><span class="timeline-kicker">WAY TO SHINE</span><h2>Timeline</h2></div><button class="timeline-filter" type="button" title="Refresh">☷</button></div>`+(me?`<form class="timeline-composer" id="timelineForm"><div class="timeline-compose-top"><div class="timeline-avatar" style="${me.photo?'background-image:url('+encodeURI(me.photo)+')':''}">${me.photo?'':esc(initials(me.name))}</div><textarea id="postText" maxlength="1000" placeholder="${esc(me.name)} กำลังคิดอะไรอยู่?" required></textarea></div><div class="timeline-compose-tools"><input id="postMedia" type="url" placeholder="ลิงก์รูป/วิดีโอ (ถ้ามี)"><button class="timeline-post-btn">POST</button></div></form>`:'')+`<div class="timeline-list">${list.length?list.map(card).join(''):`<div class="timeline-empty"><div>✦</div><b>ยังไม่มีโพสต์</b><span>${me?'เริ่มโพสต์แรกของคุณได้เลย':'โพสต์จากสมาชิกจะแสดงที่นี่'}</span></div>`}</div>`;
const form=$('#timelineForm',root);if(form)form.onsubmit=e=>{e.preventDefault();const me=current();if(!me)return;const arr=posts();arr.push({id:'post-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),name:me.name,username:me.username,group:me.group,photo:me.photo||'',text:$('#postText',root).value.trim(),media:$('#postMedia',root).value.trim(),createdAt:Date.now(),stars:0,comments:0});localStorage.setItem(KEY,JSON.stringify(arr));render(root,group)};
$$('[data-star]',root).forEach(btn=>btn.onclick=()=>{const arr=posts(),p=arr.find(x=>x.id===btn.dataset.star);if(!p)return;const star=Number(localStorage.getItem('wts_star')||0);if(star<1)return alert('STAR ไม่พอ');localStorage.setItem('wts_star',String(star-1));p.stars=Number(p.stars||0)+1;localStorage.setItem(KEY,JSON.stringify(arr));render(root,group)});
$$('[data-comment]',root).forEach(btn=>btn.onclick=()=>{const arr=posts(),p=arr.find(x=>x.id===btn.dataset.comment);if(!p)return;const c=prompt('เขียนความคิดเห็น');if(c===null)return;p.comments=Number(p.comments||0)+1;localStorage.setItem(KEY,JSON.stringify(arr));render(root,group)});
}
function boot(){ $$('.timeline').forEach(r=>render(r,r.dataset.group||'ALL')) }document.addEventListener('DOMContentLoaded',boot);window.WTSTimeline={render,posts};
})();